// Generated by CoffeeScript 1.9.3
(function() {
  var Map, Tracking, Ui, serverHost, serverPort,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  serverHost = "http://secondline-server.herokuapp.com";

  serverPort = 80;

  Map = (function() {
    function Map() {
      var center;
      center = new google.maps.LatLng(29.947877, -90.114755);
      this.marker = null;
      this.map = new google.maps.Map(document.getElementById("map-canvas"), {
        disableDefaultUI: true,
        draggable: false,
        zoom: 15,
        center: center,
        mapTypeId: google.maps.MapTypeId.ROADMAP
      });
      this.route = new google.maps.KmlLayer({
        url: "http://www.google.com/maps/d/u/0/kml?mid=zKsXt-YMXKYU.k5JzyY_3LEOo"
      });
      this.route.setMap(this.map);
    }

    Map.prototype.setPosition = function(lat, lng) {
      var position;
      if (this.marker != null) {
        this.marker.setMap(null);
        this.marker = null;
      }
      position = new google.maps.LatLng(lat, lng);
      this.marker = new google.maps.Marker({
        position: position,
        map: this.map,
        title: "position"
      });
      this.map.setCenter(position);
      return this.map.setZoom(15);
    };

    Map.prototype.clearPosition = function() {
      if (this.marker != null) {
        this.marker.setMap(null);
        return this.marker = null;
      }
    };

    return Map;

  })();

  Ui = (function() {
    function Ui() {
      this.onClear = bind(this.onClear, this);
      this.onPosition = bind(this.onPosition, this);
    }

    Ui.prototype.start = function() {
      this.map = new Map;
      this.socket = io.connect(serverHost, {
        port: serverPort
      });
      this.socket.on("position", this.onPosition);
      this.socket.on("clear", this.onClear);
      return $("#position").text("Waiting for position..");
    };

    Ui.prototype.onPosition = function(position) {
      $("#position").html("Latitude: " + position.latitude + "<br/>\nLongitude: " + position.longitude);
      return this.map.setPosition(position.latitude, position.longitude);
    };

    Ui.prototype.onClear = function() {
      return this.map.clearPosition();
    };

    return Ui;

  })();

  Tracking = (function() {
    function Tracking() {
      this.onResume = bind(this.onResume, this);
      this.onPause = bind(this.onPause, this);
      this.onFailure = bind(this.onFailure, this);
      this.onPosition = bind(this.onPosition, this);
      this.getCurrentPosition = bind(this.getCurrentPosition, this);
      this.reportUrl = serverHost + "/report";
      this.clearUrl = serverHost + "/clear";
      this.pollingInterval = 1 * 60 * 1000;
      document.addEventListener("pause", this.onPause, false);
      document.addEventListener("resume", this.onResume, false);
    }

    Tracking.prototype.configure = function() {
      var ref;
      this.bgGeo = ((ref = window.plugins) != null ? ref.backgroundGeoLocation : void 0) || {
        configure: function() {
          return console.log("geo configure");
        },
        start: function() {
          return console.log("geo start");
        },
        stop: function() {
          return console.log("geo stop");
        },
        finish: function() {
          return console.log("geo finish");
        }
      };
      return this.bgGeo.configure(this.onPosition, this.onFailure, {
        url: this.reportUrl,
        desiredAccuracy: 0,
        stationaryRadius: 20,
        distanceFilter: 30
      });
    };

    Tracking.prototype.getCurrentPosition = function() {
      return window.navigator.geolocation.getCurrentPosition(this.onPosition, this.onFailure);
    };

    Tracking.prototype.startForegroundTracker = function() {
      this.getCurrentPosition();
      return this.foregroundTracker = setInterval(this.getCurrentPosition, this.pollingInterval);
    };

    Tracking.prototype.stopForegroundTracker = function() {
      if (this.foregroundTracker != null) {
        return clearInterval(this.foregroundTracker);
      }
    };

    Tracking.prototype.setupUi = function() {
      $("#start").removeAttr("disabled");
      return $("#start").click((function(_this) {
        return function() {
          if ($("#start").hasClass("btn-success")) {
            _this.startForegroundTracker();
            return $("#start").removeClass("btn-success").addClass("btn-danger").text("Stop Tracking");
          } else {
            $.post(_this.clearUrl);
            _this.stopForegroundTracker();
            $("#position").text("Waiting for position..");
            return $("#start").removeClass("btn-danger").addClass("btn-success").text("Start Tracking");
          }
        };
      })(this));
    };

    Tracking.prototype.start = function() {
      this.configure();
      return this.setupUi();
    };

    Tracking.prototype.onPosition = function(position) {
      if ($("#start").hasClass("btn-success")) {
        return;
      }
      position = position.coords || position;
      $.post(this.reportUrl, {
        location: position
      }, null, "json");
      return this.bgGeo.finish();
    };

    Tracking.prototype.onFailure = function(error) {
      return console.log("error", error);
    };

    Tracking.prototype.onPause = function() {
      if (!$("#start").hasClass("btn-danger")) {
        return;
      }
      return this.bgGeo.start();
    };

    Tracking.prototype.onResume = function() {
      return this.bgGeo.stop();
    };

    return Tracking;

  })();

  window.Tracker = (function() {
    function Tracker() {
      this.onReady = bind(this.onReady, this);
      document.addEventListener("deviceready", this.onReady, false);
    }

    Tracker.prototype.onReady = function() {
      this.ui = new Ui;
      this.tracking = new Tracking;
      this.ui.start();
      return this.tracking.start();
    };

    return Tracker;

  })();

}).call(this);
